/**
 * Enemy sprite — single-figure (no paper-doll composition).
 *
 * v1.1 authors one Enemy: a small horned imp/goblin reading as "monster"
 * (per the brief). All colours are literal — Enemies are content, not
 * customizable, so no palette slots. Four poses required by the API:
 *   - idle      : neutral pose, baseline silhouette
 *   - casting   : arms raised, mouth open, glowing eyes brighten
 *   - hit       : recoils backward, eyes squint
 *   - defeated  : intentionally `null` so the renderer applies the
 *                 desaturation + alpha effect to the idle sprite
 *                 (per ADR-0006 §"Defeated is implemented as desaturation
 *                 + fade applied to the Idle pose…")
 *
 * Sprite size: 16 wide × 24 tall.
 *
 * Pixel legend:
 *   .  transparent
 *   K  outline       #000000
 *   g  body green    #5a8a3e
 *   d  body dark     #3a5a28   (shading + claws)
 *   e  eye glow      #ffd24a
 *   f  fang white    #f0e6c8
 *   h  horn brown    #2a1810
 */

import type { AsciiSprite } from '../decoder';
import { decodePixelArt } from '../decoder';
import type { EnemyPose } from '../api';

const ENEMY_PALETTE = {
  '.': 'transparent',
  K: '#000000',
  g: '#5a8a3e',
  d: '#3a5a28',
  e: '#ffd24a',
  f: '#f0e6c8',
  h: '#2a1810',
} as const;

// Idle: stocky imp, two horns, glowing eyes, fanged mouth, clawed hands at sides.
const ENEMY_IDLE = decodePixelArt(
  `
..Kh......hK....
..KhK....KhK....
..KhKKKKKKhK....
..KKgggggggK....
.KggggggggggK...
.KggdggggdggK...
.KgggKeeKgggK...
.KggKeeeeKggK...
.KgggKfKgggKK...
.KggggffggggK...
.KggggggggggK...
KggggdggdggggK..
KggggggggggggK..
.KggggggggggK...
.KggggggggggK...
.KggggggggggK...
..KggggggggK....
..KdggggggdK....
..KdgggggddK....
..KdgggggddK....
..KKgggggKK.....
..KKgggggKK.....
..KKK...KKK.....
..KKK...KKK.....
`,
  ENEMY_PALETTE,
);

// Casting: arms raised, mouth open wider, eyes brighter (we keep yellow,
// the brightness comes from animation), horns the same.
const ENEMY_CASTING = decodePixelArt(
  `
KhK......KhK....
KhK......KhK....
KhKKKKKKKKhK....
.KKgggggggKK....
KggggggggggggK..
KggdggggggdggK..
KgggKeeKKeeKggK.
KggKeeeeeeKggK..
.KggKfffKggggK..
.KgggfffggggK...
.KggggfgggggK...
.KggggggggggK...
.KggdggggdggK...
.KggggggggggK...
.KggggggggggK...
.KggggggggggK...
..KggggggggK....
..KdggggggdK....
..KdgggggddK....
..KdgggggddK....
..KKgggggKK.....
..KKgggggKK.....
..KKK...KKK.....
..KKK...KKK.....
`,
  ENEMY_PALETTE,
);

// Hit: recoils — head bows, body tilts, one horn tipped back, eyes squint
// (no eye glow, just dark).
const ENEMY_HIT = decodePixelArt(
  `
.Kh.......h.....
.KhK.....KhK....
..KhKKKKKhKK....
..KKgggggggK....
..KgggggggggK...
.KgggdgggdgggK..
.KgggKKKKKgggK..
.KggggggggggK...
.KgggKfKggggK...
.KggggfgggggK...
.KggggggggggK...
KgggdgggdggggK..
KggggggggggggK..
.KggggggggggK...
.KggggggggggK...
.KggggggggggK...
..KggggggggK....
..KdggggggdK....
..KdgggggddK....
..KdgggggddK....
..KKgggggKK.....
..KKgggggKK.....
..KKK...KKK.....
..KKK...KKK.....
`,
  ENEMY_PALETTE,
);

/**
 * Defeated is intentionally `null` — see ADR-0006. The Encounter Canvas
 * renderer is expected to apply desaturation + reduced alpha to the idle
 * sprite when it sees `null` here. Surface a `null` explicitly rather than
 * silently returning idle, so the renderer knows to apply the effect.
 */
export const enemySprites: Readonly<
  Record<EnemyPose, AsciiSprite | null>
> = {
  idle: ENEMY_IDLE,
  casting: ENEMY_CASTING,
  hit: ENEMY_HIT,
  defeated: null,
};
