/**
 * Enemy sprite — Phase 2 (transformed/enraged variant).
 *
 * Visually distinct from the Phase 1 sprite so the player can tell at a
 * glance that the Enemy has changed form when the HP threshold crosses.
 * Per CONTEXT.md "Phase Transformation".
 *
 * Same general silhouette as Phase 1 (same creature) but:
 *   - Deep red body instead of green ("blood form").
 *   - Glowing red eyes instead of yellow ("rage").
 *   - Longer, sharper horns.
 *   - Claws bared in idle.
 *
 * Sprite size: 16 wide × 24 tall (same as Phase 1).
 *
 * Pixel legend:
 *   .  transparent
 *   K  outline       #000000
 *   r  body red      #a02828
 *   d  body dark     #5a1414   (shading + claws)
 *   e  eye glow      #ff4444
 *   f  fang white    #f0e6c8
 *   h  horn dark     #2a1010
 */

import type { AsciiSprite } from '../decoder';
import { decodePixelArt } from '../decoder';
import type { EnemyPose } from '../api';

const ENEMY_PHASE2_PALETTE = {
  '.': 'transparent',
  K: '#000000',
  r: '#a02828',
  d: '#5a1414',
  e: '#ff4444',
  f: '#f0e6c8',
  h: '#2a1010',
} as const;

// Idle: longer horns, glowing red eyes, fangs slightly larger, claws splayed.
const ENEMY_IDLE_P2 = decodePixelArt(
  `
.Kh......hK.....
.KhK....KhK.....
.KhK....KhK.....
.KhKKKKKKhK.....
.KKrrrrrrrK.....
KrrrrrrrrrrK....
KrrrdrrrrdrrK...
KrrrKeeKrrrrK...
KrrKeeeeKrrrK...
KrrrKfKrrrrKK...
KrrrffrrrrrrK...
KrrrrrrrrrrrK...
KrrrdrrdrrrrK...
KrrrrrrrrrrrK...
.KrrrrrrrrrK....
.KrrrrrrrrrK....
.KdrrrrrrrdK....
.KdrrrrrrrdK....
.KdrrrrrrrdK....
.KKrrrrrrKK.....
.KKrrrrrrKK.....
KKK.....KKKK....
KKK.....KKKK....
KKK.....KKKK....
`,
  ENEMY_PHASE2_PALETTE,
);

// Casting: arms up, mouth wider, eyes more intense, claws raised.
const ENEMY_CASTING_P2 = decodePixelArt(
  `
Kh........hK....
Kh........hK....
Kh.K....K.hK....
KKKKKKKKKKKK....
.KrrrrrrrrK.....
KrrrrrrrrrrK....
KrrdrrrrrrdrK...
KrrKeeKKeeKrK...
KrrKeeeeeeKrK...
KrrKffffKrrrK...
KrrrffffrrrrK...
KrrrrrrrrrrrK...
KrrrdrrrrdrrK...
.KrrrrrrrrrK....
.KrrrrrrrrrK....
.KrrrrrrrrrK....
.KrrrrrrrrrK....
.KdrrrrrrrdK....
.KdrrrrrrrdK....
.KKrrrrrrKK.....
.KKrrrrrrKK.....
KKK.....KKKK....
KKK.....KKKK....
KKK.....KKKK....
`,
  ENEMY_PHASE2_PALETTE,
);

// Hit: recoils — body tilts, horns angle back, eyes darken to slits.
const ENEMY_HIT_P2 = decodePixelArt(
  `
Kh........h.....
KhK......KhK....
KhK......KhK....
.KhKKKKKKhK.....
.KKrrrrrrrK.....
.KrrrrrrrrrK....
KrrrdrrrrdrrK...
KrrrKKKKKrrrK...
KrrrrrrrrrrrK...
KrrrKfKrrrrrK...
KrrrrffrrrrrK...
KrrrrrrrrrrrK...
KrrrdrrrrdrrK...
.KrrrrrrrrrK....
.KrrrrrrrrrK....
.KrrrrrrrrrK....
.KrrrrrrrrrK....
.KdrrrrrrrdK....
.KdrrrrrrrdK....
.KKrrrrrrKK.....
.KKrrrrrrKK.....
KKK.....KKKK....
KKK.....KKKK....
KKK.....KKKK....
`,
  ENEMY_PHASE2_PALETTE,
);

/**
 * Phase 2 sprite set. `defeated` stays `null` — the Defeated effect
 * (desaturation + alpha applied to idle) is independent of phase variant.
 */
export const enemyPhase2Sprites: Readonly<
  Record<EnemyPose, AsciiSprite | null>
> = {
  idle: ENEMY_IDLE_P2,
  casting: ENEMY_CASTING_P2,
  hit: ENEMY_HIT_P2,
  defeated: null,
};
