/**
 * Player cloth sprites — paper-doll cloth layer.
 *
 * v1.1 ships only `clothStyle: 'robe'`. Other styles in the type union
 * (`tunic`, `cape`) are not yet authored.
 *
 * Sprite size: 16 wide × 24 tall (matches body).
 *
 * Pixel legend:
 *   .  transparent
 *   K  outline (#000000, literal)
 *   c  cloth (@cloth slot)
 *
 * Robe: covers torso and flares out wider than legs, ending mid-shin.
 */

import type { AsciiSprite } from '../decoder';
import { decodePixelArt } from '../decoder';
import type { PlayerPose, PlayerSkin } from '../api';

const CLOTH_PALETTE = {
  '.': 'transparent',
  K: '#000000',
  c: '@cloth',
} as const;

// Robe overlays the body from the shoulders down. We leave a v-neck so the
// skin neck still reads, and we widen at the hem so it reads as a robe and
// not a sweater.
const ROBE_IDLE = decodePixelArt(
  `
................
................
................
................
................
................
................
....KccccK......
...KccccccK.....
..KccKccccKcK...
..KccKccccKcK...
..KccccccccK....
..KccccccccK....
..KccccccccK....
..KccccccccK....
..KccccccccK....
.KccccccccccK...
.KccccccccccK...
.KccccccccccK...
.KccccccccccK...
.KccccccccccK...
KccccccccccccK..
KccccccccccccK..
KKKKKKKKKKKKKK..
`,
  CLOTH_PALETTE,
);

// Hit pose: robe shifts down 1 row to match body recoil.
const ROBE_HIT = decodePixelArt(
  `
................
................
................
................
................
................
................
................
....KccccK......
...KccccccK.....
..KccKccccKcK...
..KccKccccKcK...
..KccccccccK....
..KccccccccK....
..KccccccccK....
..KccccccccK....
.KccccccccccK...
.KccccccccccK...
.KccccccccccK...
.KccccccccccK...
.KccccccccccK...
KccccccccccccK..
KccccccccccccK..
KKKKKKKKKKKKKK..
`,
  CLOTH_PALETTE,
);

// Counterattack: robe flares wider on the lead side (player leans forward).
const ROBE_COUNTERATTACK = decodePixelArt(
  `
................
................
................
................
................
................
................
....KccccK......
...KccccccK.....
KKKKccccccK.K...
..KcKccccKcK....
..KccccccccK....
..KccccccccK....
..KccccccccK....
..KccccccccK....
..KccccccccK....
.KccccccccccK...
.KccccccccccK...
.Kcc......ccK...
.Kcc......ccK...
.Kcc......ccK...
.Kcc......ccK...
KccK......KccK..
KKKK......KKKK..
`,
  CLOTH_PALETTE,
);

export const clothSprites: Record<
  PlayerSkin['clothStyle'],
  Record<PlayerPose, AsciiSprite>
> = {
  robe: {
    idle: ROBE_IDLE,
    hit: ROBE_HIT,
    counterattack: ROBE_COUNTERATTACK,
  },
  tunic: makeUnauthored('tunic'),
  cape: makeUnauthored('cape'),
};

function makeUnauthored(
  style: PlayerSkin['clothStyle'],
): Record<PlayerPose, AsciiSprite> {
  return new Proxy({} as Record<PlayerPose, AsciiSprite>, {
    get(_target, pose: string): AsciiSprite {
      throw new Error(
        `player-cloth: clothStyle '${style}' is not yet authored (requested pose '${pose}').`,
      );
    },
  });
}
