/**
 * Player hair sprites — paper-doll hair layer.
 *
 * v1.1 ships only `hairStyle: 'short'`. Other styles in the type union
 * (`long`, `curly`, `bald`) are not yet authored; the composer surfaces
 * the absence via a clear "not yet authored" error.
 *
 * Sprite size: 16 wide × 24 tall (matches body so layers align 1:1).
 *
 * Pixel legend:
 *   .  transparent
 *   K  outline (#000000, literal)
 *   h  hair (@hair slot)
 *
 * Short hair: a cap of hair across the top of the head + small sideburns.
 */

import type { AsciiSprite } from '../decoder';
import { decodePixelArt } from '../decoder';
import type { PlayerPose, PlayerSkin } from '../api';

const HAIR_PALETTE = {
  '.': 'transparent',
  K: '#000000',
  h: '@hair',
} as const;

const SHORT_IDLE = decodePixelArt(
  `
....KKKKKK......
...KhhhhhhK.....
...KhhhhhhK.....
...Kh....hK.....
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
`,
  HAIR_PALETTE,
);

const SHORT_HIT = decodePixelArt(
  `
................
....KKKKKK......
...KhhhhhhK.....
...Kh....hK.....
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
`,
  HAIR_PALETTE,
);

const SHORT_COUNTERATTACK = decodePixelArt(
  `
....KKKKKK......
...KhhhhhhK.....
...KhhhhhhK.....
...Kh....hK.....
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
`,
  HAIR_PALETTE,
);

export const hairSprites: Record<
  PlayerSkin['hairStyle'],
  Record<PlayerPose, AsciiSprite>
> = {
  short: {
    idle: SHORT_IDLE,
    hit: SHORT_HIT,
    counterattack: SHORT_COUNTERATTACK,
  },
  long: makeUnauthored('long'),
  curly: makeUnauthored('curly'),
  bald: makeUnauthored('bald'),
};

function makeUnauthored(
  style: PlayerSkin['hairStyle'],
): Record<PlayerPose, AsciiSprite> {
  return new Proxy({} as Record<PlayerPose, AsciiSprite>, {
    get(_target, pose: string): AsciiSprite {
      throw new Error(
        `player-hair: hairStyle '${style}' is not yet authored (requested pose '${pose}').`,
      );
    },
  });
}
