/**
 * Player weapon sprites — paper-doll weapon layer.
 *
 * v1.1 ships only `weapon: 'none'`, authored as a fully-transparent
 * same-sized sprite per pose. The composer therefore needs no special
 * case for "no weapon".
 *
 * Other weapons (`staff`, `wand`) are not yet authored.
 *
 * Sprite size: 16 wide × 24 tall (matches body).
 *
 * Pixel legend:
 *   .  transparent
 */

import type { AsciiSprite } from '../decoder';
import { decodePixelArt } from '../decoder';
import type { PlayerPose, PlayerSkin } from '../api';

const WEAPON_PALETTE = { '.': 'transparent' } as const;

const EMPTY_16x24 = `
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
`;

const NONE_IDLE = decodePixelArt(EMPTY_16x24, WEAPON_PALETTE);
const NONE_HIT = decodePixelArt(EMPTY_16x24, WEAPON_PALETTE);
const NONE_COUNTERATTACK = decodePixelArt(EMPTY_16x24, WEAPON_PALETTE);

export const weaponSprites: Record<
  PlayerSkin['weapon'],
  Record<PlayerPose, AsciiSprite>
> = {
  none: {
    idle: NONE_IDLE,
    hit: NONE_HIT,
    counterattack: NONE_COUNTERATTACK,
  },
  staff: makeUnauthored('staff'),
  wand: makeUnauthored('wand'),
};

function makeUnauthored(
  style: PlayerSkin['weapon'],
): Record<PlayerPose, AsciiSprite> {
  return new Proxy({} as Record<PlayerPose, AsciiSprite>, {
    get(_target, pose: string): AsciiSprite {
      throw new Error(
        `player-weapon: weapon '${style}' is not yet authored (requested pose '${pose}').`,
      );
    },
  });
}
