/**
 * Player body sprites — paper-doll base layer.
 *
 * v1.1 ships only `bodyShape: 'male'`. Three poses authored: idle, hit,
 * counterattack. `'female'` is intentionally not authored (per the brief
 * and ADR-0006); requesting it throws a clear "not yet authored" error.
 *
 * Sprite size: 16 wide × 24 tall, logical pixels.
 *
 * Pixel legend:
 *   .  transparent
 *   K  outline (#000000, literal)
 *   s  skin (@skin slot)
 *   e  eye (@eye slot)
 *
 * Hair, cloth and weapon are drawn by *separate* layers above this body;
 * the body sprite leaves room on the head/torso/hand for them.
 */

import type { AsciiSprite } from '../decoder';
import { decodePixelArt } from '../decoder';
import type { PlayerPose, PlayerSkin } from '../api';

const BODY_PALETTE = {
  '.': 'transparent',
  K: '#000000',
  s: '@skin',
  e: '@eye',
} as const;

// 16x24 male idle: head up top, arms slack at sides, feet planted.
const MALE_IDLE = decodePixelArt(
  `
....KKKKKK......
...KssssssK.....
...KssssssK.....
...KsKssKsK.....
...KsessesK.....
...KssssssK.....
....KssssK......
....KssssK......
...KssssssK.....
..KssssssssK....
..KsKssssKsK....
..KsKssssKsK....
..KssssssssK....
..KssssssssK....
..KssssssssK....
..KssssssssK....
...KssssssK.....
...KssssssK.....
...Ks....sK.....
...Ks....sK.....
...Ks....sK.....
...Ks....sK.....
..KKK....KKK....
..KKK....KKK....
`,
  BODY_PALETTE,
);

// Hit: head tilts back, arms recoil outward, body shrinks downward 1px.
const MALE_HIT = decodePixelArt(
  `
................
....KKKKKK......
...KssssssK.....
...KsKssKsK.....
...KsessesK.....
...KssssssK.....
....KssssK......
....KssssK......
.KssssssssssK...
.KssssssssssK...
..KssssssssK....
..KsKssssKsK....
..KsKssssKsK....
..KssssssssK....
..KssssssssK....
..KssssssssK....
..KssssssssK....
...KssssssK.....
...KssssssK.....
...Ks....sK.....
...Ks....sK.....
...Ks....sK.....
..KKK....KKK....
..KKK....KKK....
`,
  BODY_PALETTE,
);

// Counterattack: leans forward 1px, arm extends to the left toward enemy,
// stance widens. The body faces enemy (which is on the left side of canvas).
const MALE_COUNTERATTACK = decodePixelArt(
  `
....KKKKKK......
...KssssssK.....
...KssssssK.....
...KsKssKsK.....
...KeessssK.....
...KssssssK.....
....KssssK......
....KssssK......
KssssssssssK....
KssssssssssK....
KKKssssssK.K....
..KsKssssKsK....
..KssssssssK....
..KssssssssK....
..KssssssssK....
..KssssssssK....
...KssssssK.....
...KssssssK.....
..Kss....ssK....
..Kss....ssK....
..Kss....ssK....
..Kss....ssK....
.KKK......KKK...
.KKK......KKK...
`,
  BODY_PALETTE,
);

export const bodySprites: Record<
  PlayerSkin['bodyShape'],
  Record<PlayerPose, AsciiSprite>
> = {
  male: {
    idle: MALE_IDLE,
    hit: MALE_HIT,
    counterattack: MALE_COUNTERATTACK,
  },
  // v1.1: 'female' intentionally not authored. The lookup in composition.ts
  // surfaces the absence via a clear error rather than silently falling back.
  // See README of this milestone — adding the variant is content-only.
  female: new Proxy({} as Record<PlayerPose, AsciiSprite>, {
    get(_target, pose: string): AsciiSprite {
      throw new Error(
        `player-body: bodyShape 'female' is not yet authored (requested pose '${pose}'). Add bodySprites.female.${pose} to ship it.`,
      );
    },
  }),
};
